package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/wangkebin/kbds-ref-graphql/database"
	"github.com/wangkebin/kbds-ref-graphql/graph/model"
	log "github.com/wangkebin/kbds-ref-graphql/logger"
)

// SearchFiles is the resolver for the SearchFiles field.
func (r *queryResolver) SearchFiles(ctx context.Context, name *string) ([]*model.FileInfo, error) {
	l := ctx.Value("logger").(*log.Log)
	db := database.Connect(l)
	res, err := database.SearchFiles(name, db, l)
	if err != nil {
		l.Errorf("failed to search files", err)
		return nil, err
	}
	return res, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
