// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FileInfo struct {
	ID        string  `json:"id" gorm:"column:id;PRIMARY_KEY"`
	Location  string  `json:"location" gorm:"column:loc"`
	Size      *int    `json:"size,omitempty" gorm:"column:size"`
	Name      *string `json:"name,omitempty" gorm:"column:name"`
	MachineID string  `json:"machineId" gorm:"column:machine_id"`
}

type Machine struct {
	ID       string `json:"id" gorm:"column:id;PRIMARY_KEY"`
	Name     string `json:"name" gorm:"column:name"`
	Writable bool   `json:"writable" gorm:"column:writable"`
}

type MachineFiles struct {
	Machine *Machine    `json:"machine,omitempty"`
	Files   []*FileInfo `json:"files,omitempty"`
}

type Query struct {
}
